function populateRegisteredStructure()

data = {
    
{'GCOS Monthly Summaries from DWD', ...
'Summaries from the global climate observing system as reported by Deutscher Wetterdienst', ...
{'TAVG - Monthly', 'TMIN - Monthly', 'TMAX - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'GHCN Monthly version 2', ...
'Version 2 of NOAA''s Global Historical Climatology Network - Monthly', ...
{'TAVG - Monthly', 'TMIN - Monthly', 'TMAX - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'GHCN Monthly version 3', ...
'Version 3 of NOAA''s Global Historical Climatology Network - Monthly', ...
{'TAVG - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'GHCN Daily', ...
'Version 2 of NOAA''s Global Historical Climatology Network - Daily', ...
{'TAVG - Daily', 'TMAX - Daily', 'TMIN - Daily'}, ...
{'LATEST', 'Most recently processed version' } }

{'US First Order Summary of the Day', ...
'United States daily summary reports from first order weather stations', ...
{'TAVG - Daily', 'TMAX - Daily', 'TMIN - Daily'}, ...
{'LATEST', 'Most recently processed version' } }

{'US Cooperative Summary of the Day', ...
'United States daily summary reports from volunteer cooperative weather stations', ...
{'TAVG - Daily', 'TMAX - Daily', 'TMIN - Daily'}, ...
{'LATEST', 'Most recently processed version' } }

{'Hadley Centre / CRU partial data collection', ...
'The publicly released portion of the Hadley Centre and Climatic Research data collection', ...
{'TAVG - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'US Cooperative Summary of the Month', ...
'United States monthly summares from volunteer cooperative weather stations', ...
{'TAVG - Monthly', 'TMAX - Monthly', 'TMIN - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'US Historical Climatology Network - Monthly', ...
'United States Historical Climatology Network monthly weather reports', ...
{'TAVG - Monthly', 'TMAX - Monthly', 'TMIN - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'World Monthly Surface Station Climatology', ...
'United States Historical Climatology Network monthly weather reports', ...
{'TAVG - Daily'}, ...
{'LATEST', 'Most recently processed version' } }

{'Scientific Committee on Antarctic Research', ...
'Temperature data collected at Antarctic and Southern Ocean research stations and automated outposts', ...
{'TAVG - Monthly', 'OT00 - Monthly', 'OT06 - Monthly', 'OT12 - Monthly', 'OT18 - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'GSN Monthly Summaries from NOAA', ...
'Summaries from the global surface network as reported by NOAA', ...
{'TAVG - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'Monthly Climatic Data of the World', ...
'Temperature data published in the Monthly Climatic Data of the World', ...
{'TAVG - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'World Weather Records', ...
'Temperature data published in the decadal World Weather Records', ...
{'TAVG - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'Colonial Era Weather Archive', ...
'Temperature data collected as part of the Colonial Era Weather Archive', ...
{'TAVG - Monthly'}, ...
{'LATEST', 'Most recently processed version' } }

{'Global Summary of the Day', ...
'Weather observations included in the Global Summary of the Day', ...
{'TAVG - Daily', 'TMAX - Daily', 'TMIN - Daily'}, ...
{'LATEST', 'Most recently processed version' } }

{'Berkeley Earth Merged Dataset - version 1', ...
'Merged data product created by Berkeley Earth', ...
{'TAVG - Daily', 'TMAX - Daily', 'TMIN - Daily', 'TOBS - Daily', ...
 'TAVG - Monthly', 'TMAX - Monthly', 'TMIN - Monthly', 'TOBS - Monthly'}, ...
{'LATEST', 'Most recently processed complete version' }, ...
{'LATEST - Single-valued', 'Most recently processed version with multi-valued days and sites collapsed to single record' }, ...
{'LATEST - Detrended', 'Most recently processed version single-valued with annual cycle removed' } }

{'Berkeley Earth Merged Dataset - version 2', ...
'Merged data product created by Berkeley Earth', ...
{'TAVG - Daily', 'TMAX - Daily', 'TMIN - Daily', 'TOBS - Daily', ...
 'TAVG - Monthly', 'TMAX - Monthly', 'TMIN - Monthly', 'TOBS - Monthly'}, ...
{'LATEST', 'Most recently processed complete version' }, ...
{'LATEST - Single-valued', 'Most recently processed version with multi-valued days and sites collapsed to single record' }, ...
{'LATEST - Detrended', 'Most recently processed version single-valued with annual cycle removed' } }

{'Berkeley Earth Merged Dataset - Samples', ...
'Merged data product created by Berkeley Earth', ...
{'TAVG - Daily', 'TMAX - Daily', 'TMIN - Daily', 'TOBS - Daily', ...
 'TAVG - Monthly', 'TMAX - Monthly', 'TMIN - Monthly', 'TOBS - Monthly'}, ...
{'Version 1 - 0.5% - Complete', '0.5% sample of Berkeley Earth version 1 with all records' }, ...
{'Version 1 - 0.5% - Single-valued', '0.5% sample of Berkeley Earth version 1 with multi-valued records collapsed' }, ...
{'Version 1 - 0.5% - Detrended', '0.5% sample of Berkeley Earth version 1 with seasonality removed' }, ...
{'Version 1 - 2% A - Complete', '2% sample A of Berkeley Earth version 1 with all records' }, ...
{'Version 1 - 2% A - Single-valued', '2% sample A of Berkeley Earth version 1 with multi-valued records collapsed' }, ...
{'Version 1 - 2% A - Detrended', '2% sample A of Berkeley Earth version 1 with seasonality removed' }, ...
{'Version 1 - 2% B - Complete', '2% sample B of Berkeley Earth version 1 with all records' }, ...
{'Version 1 - 2% B - Single-valued', '2% sample B of Berkeley Earth version 1 with multi-valued records collapsed' }, ...
{'Version 1 - 2% B - Detrended', '2% sample B of Berkeley Earth version 1 with seasonality removed' }, ...
{'Version 1 - 2% C - Complete', '2% sample C of Berkeley Earth version 1 with all records' }, ...
{'Version 1 - 2% C - Single-valued', '2% sample C of Berkeley Earth version 1 with multi-valued records collapsed' }, ...
{'Version 1 - 2% C - Detrended', '2% sample C of Berkeley Earth version 1 with seasonality removed' } }

};

for k = 1:length(data)
    name = data{k}{1};
    description = data{k}{2};
    
    defineDataCollection( name, description, true );
    types = data{k}{3};
    for j = 1:length(types);
        defineDataType( name, types{j}, '', true );
        for m = 4:length(data{k})
            defineVersion( name, types{j}, data{k}{m}{1}, data{k}{m}{2}, true );
        end
    end
end